/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityRouteImport } from './routes/city'
import { Route as CollaborateRouteImport } from './routes/collaborate'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MusicRouteImport } from './routes/music'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as ApiCommitsDotjsonRouteImport } from './routes/api/commits[.]json'
import { Route as ApiUpdatesDotjsonRouteImport } from './routes/api/updates[.]json'
import { Route as ApiWorldDotjsonRouteImport } from './routes/api/world[.]json'
import { Route as BibleIndexRouteImport } from './routes/bible/index'
import { Route as BibleSlugRouteImport } from './routes/bible/$slug'
import { Route as BibleFoundationsRouteImport } from './routes/bible/foundations'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as GallerySlugRouteImport } from './routes/gallery/$slug'
import { Route as GalleryPackRouteImport } from './routes/gallery/pack'
import { Route as BibleCompanionsIndexRouteImport } from './routes/bible/companions/index'
import { Route as BibleCompanionsDocRouteImport } from './routes/bible/companions/$doc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborateRoute = CollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommitsDotjsonRoute = ApiCommitsDotjsonRouteImport.update({
  id: '/api/commits.json',
  path: '/api/commits.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdatesDotjsonRoute = ApiUpdatesDotjsonRouteImport.update({
  id: '/api/updates.json',
  path: '/api/updates.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorldDotjsonRoute = ApiWorldDotjsonRouteImport.update({
  id: '/api/world.json',
  path: '/api/world.json',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/bible/',
  path: '/bible/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleSlugRoute = BibleSlugRouteImport.update({
  id: '/bible/$slug',
  path: '/bible/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleFoundationsRoute = BibleFoundationsRouteImport.update({
  id: '/bible/foundations',
  path: '/bible/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/gallery/$slug',
  path: '/gallery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryPackRoute = GalleryPackRouteImport.update({
  id: '/gallery/pack',
  path: '/gallery/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleCompanionsIndexRoute = BibleCompanionsIndexRouteImport.update({
  id: '/bible/companions/',
  path: '/bible/companions/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleCompanionsDocRoute = BibleCompanionsDocRouteImport.update({
  id: '/bible/companions/$doc',
  path: '/bible/companions/$doc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/collaborate': typeof CollaborateRoute
  '/credits': typeof CreditsRoute
  '/culture': typeof CultureRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/music': typeof MusicRoute
  '/search': typeof SearchRoute
  '/systems': typeof SystemsRoute
  '/updates': typeof UpdatesRoute
  '/api/commits.json': typeof ApiCommitsDotjsonRoute
  '/api/updates.json': typeof ApiUpdatesDotjsonRoute
  '/api/world.json': typeof ApiWorldDotjsonRoute
  '/bible/$slug': typeof BibleSlugRoute
  '/bible/foundations': typeof BibleFoundationsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/gallery/pack': typeof GalleryPackRoute
  '/bible/': typeof BibleIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/bible/companions/$doc': typeof BibleCompanionsDocRoute
  '/bible/companions/': typeof BibleCompanionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/collaborate': typeof CollaborateRoute
  '/credits': typeof CreditsRoute
  '/culture': typeof CultureRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/music': typeof MusicRoute
  '/search': typeof SearchRoute
  '/systems': typeof SystemsRoute
  '/updates': typeof UpdatesRoute
  '/api/commits.json': typeof ApiCommitsDotjsonRoute
  '/api/updates.json': typeof ApiUpdatesDotjsonRoute
  '/api/world.json': typeof ApiWorldDotjsonRoute
  '/bible/$slug': typeof BibleSlugRoute
  '/bible/foundations': typeof BibleFoundationsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/gallery/pack': typeof GalleryPackRoute
  '/bible': typeof BibleIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/bible/companions/$doc': typeof BibleCompanionsDocRoute
  '/bible/companions': typeof BibleCompanionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/collaborate': typeof CollaborateRoute
  '/credits': typeof CreditsRoute
  '/culture': typeof CultureRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/music': typeof MusicRoute
  '/search': typeof SearchRoute
  '/systems': typeof SystemsRoute
  '/updates': typeof UpdatesRoute
  '/api/commits.json': typeof ApiCommitsDotjsonRoute
  '/api/updates.json': typeof ApiUpdatesDotjsonRoute
  '/api/world.json': typeof ApiWorldDotjsonRoute
  '/bible/$slug': typeof BibleSlugRoute
  '/bible/foundations': typeof BibleFoundationsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/gallery/pack': typeof GalleryPackRoute
  '/bible/': typeof BibleIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/bible/companions/$doc': typeof BibleCompanionsDocRoute
  '/bible/companions/': typeof BibleCompanionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/city'
    | '/collaborate'
    | '/credits'
    | '/culture'
    | '/llms.txt'
    | '/music'
    | '/search'
    | '/systems'
    | '/updates'
    | '/api/commits.json'
    | '/api/updates.json'
    | '/api/world.json'
    | '/bible/$slug'
    | '/bible/foundations'
    | '/gallery/$slug'
    | '/gallery/pack'
    | '/bible/'
    | '/gallery/'
    | '/bible/companions/$doc'
    | '/bible/companions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/city'
    | '/collaborate'
    | '/credits'
    | '/culture'
    | '/llms.txt'
    | '/music'
    | '/search'
    | '/systems'
    | '/updates'
    | '/api/commits.json'
    | '/api/updates.json'
    | '/api/world.json'
    | '/bible/$slug'
    | '/bible/foundations'
    | '/gallery/$slug'
    | '/gallery/pack'
    | '/bible'
    | '/gallery'
    | '/bible/companions/$doc'
    | '/bible/companions'
  id:
    | '__root__'
    | '/'
    | '/city'
    | '/collaborate'
    | '/credits'
    | '/culture'
    | '/llms.txt'
    | '/music'
    | '/search'
    | '/systems'
    | '/updates'
    | '/api/commits.json'
    | '/api/updates.json'
    | '/api/world.json'
    | '/bible/$slug'
    | '/bible/foundations'
    | '/gallery/$slug'
    | '/gallery/pack'
    | '/bible/'
    | '/gallery/'
    | '/bible/companions/$doc'
    | '/bible/companions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityRoute: typeof CityRoute
  CollaborateRoute: typeof CollaborateRoute
  CreditsRoute: typeof CreditsRoute
  CultureRoute: typeof CultureRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MusicRoute: typeof MusicRoute
  SearchRoute: typeof SearchRoute
  SystemsRoute: typeof SystemsRoute
  UpdatesRoute: typeof UpdatesRoute
  ApiCommitsDotjsonRoute: typeof ApiCommitsDotjsonRoute
  ApiUpdatesDotjsonRoute: typeof ApiUpdatesDotjsonRoute
  ApiWorldDotjsonRoute: typeof ApiWorldDotjsonRoute
  BibleSlugRoute: typeof BibleSlugRoute
  BibleFoundationsRoute: typeof BibleFoundationsRoute
  GallerySlugRoute: typeof GallerySlugRoute
  GalleryPackRoute: typeof GalleryPackRoute
  BibleIndexRoute: typeof BibleIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  BibleCompanionsDocRoute: typeof BibleCompanionsDocRoute
  BibleCompanionsIndexRoute: typeof BibleCompanionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborate': {
      id: '/collaborate'
      path: '/collaborate'
      fullPath: '/collaborate'
      preLoaderRoute: typeof CollaborateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commits.json': {
      id: '/api/commits.json'
      path: '/api/commits.json'
      fullPath: '/api/commits.json'
      preLoaderRoute: typeof ApiCommitsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/updates.json': {
      id: '/api/updates.json'
      path: '/api/updates.json'
      fullPath: '/api/updates.json'
      preLoaderRoute: typeof ApiUpdatesDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/world.json': {
      id: '/api/world.json'
      path: '/api/world.json'
      fullPath: '/api/world.json'
      preLoaderRoute: typeof ApiWorldDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/': {
      id: '/bible/'
      path: '/bible'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$slug': {
      id: '/bible/$slug'
      path: '/bible/$slug'
      fullPath: '/bible/$slug'
      preLoaderRoute: typeof BibleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/foundations': {
      id: '/bible/foundations'
      path: '/bible/foundations'
      fullPath: '/bible/foundations'
      preLoaderRoute: typeof BibleFoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/gallery/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/pack': {
      id: '/gallery/pack'
      path: '/gallery/pack'
      fullPath: '/gallery/pack'
      preLoaderRoute: typeof GalleryPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/companions/': {
      id: '/bible/companions/'
      path: '/bible/companions'
      fullPath: '/bible/companions/'
      preLoaderRoute: typeof BibleCompanionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/companions/$doc': {
      id: '/bible/companions/$doc'
      path: '/bible/companions/$doc'
      fullPath: '/bible/companions/$doc'
      preLoaderRoute: typeof BibleCompanionsDocRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityRoute: CityRoute,
  CollaborateRoute: CollaborateRoute,
  CreditsRoute: CreditsRoute,
  CultureRoute: CultureRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MusicRoute: MusicRoute,
  SearchRoute: SearchRoute,
  SystemsRoute: SystemsRoute,
  UpdatesRoute: UpdatesRoute,
  ApiCommitsDotjsonRoute: ApiCommitsDotjsonRoute,
  ApiUpdatesDotjsonRoute: ApiUpdatesDotjsonRoute,
  ApiWorldDotjsonRoute: ApiWorldDotjsonRoute,
  BibleSlugRoute: BibleSlugRoute,
  BibleFoundationsRoute: BibleFoundationsRoute,
  GallerySlugRoute: GallerySlugRoute,
  GalleryPackRoute: GalleryPackRoute,
  BibleIndexRoute: BibleIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  BibleCompanionsDocRoute: BibleCompanionsDocRoute,
  BibleCompanionsIndexRoute: BibleCompanionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
